apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: camel-kafka-authz-rb
  namespace: strimzi
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: camel-kafka-authz-sa
  namespace: fuse
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: camel-kafka-authz-rb
  namespace: fuse
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: camel-kafka-authz-sa
  namespace: fuse
