apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: camel-kafka-authz-secret-sync
  namespace: fuse
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 10
  jobTemplate:             
    spec:
      template:
        spec:
          serviceAccountName: camel-kafka-authz-sa
          restartPolicy: Never
          containers:
          - name: cluster-ca-cert-sync
            image: openshift/origin-cli
            env:
            - name: SRC_NAMESPACE
              value: "strimzi"
            - name: DST_NAMESPACE
              value: "fuse"
            - name: SECRET_NAME
              value: "my-cluster-cluster-ca-cert"
            - name: SECRET_KEY
              value: "ca.crt"
            command: ["bash",  "-c", "export SRC=\"$(oc extract -n $SRC_NAMESPACE secrets/$SECRET_NAME --keys=$SECRET_KEY --to=-)\"; export DST=\"$(oc extract -n $DST_NAMESPACE secrets/$SECRET_NAME --keys=$SECRET_KEY --to=-)\"; if [ -n \"$SRC\" ] && [ \"$DST\" != \"$SRC\" ]; then echo 'Values differ. Syncing...'; oc create secret generic -n $DST_NAMESPACE --dry-run -o yaml $SECRET_NAME --from-literal=\"$SECRET_KEY=$SRC\" | oc apply -f -; fi;"]
          - name: alice-sync
            image: openshift/origin-cli
            env:
            - name: SRC_NAMESPACE
              value: "strimzi"
            - name: DST_NAMESPACE
              value: "fuse"
            - name: SECRET_NAME
              value: "alice"
            - name: SECRET_USER_CERT_KEY
              value: "user.crt"
            - name: SECRET_USER_KEY_KEY
              value: "user.key"
            command: ["bash",  "-c", "export SRC_CERT=\"$(oc extract -n $SRC_NAMESPACE secrets/$SECRET_NAME --keys=$SECRET_USER_CERT_KEY --to=-)\"; export SRC_KEY=\"$(oc extract -n $SRC_NAMESPACE secrets/$SECRET_NAME --keys=$SECRET_USER_KEY_KEY --to=-)\"; export DST_CERT=\"$(oc extract -n $DST_NAMESPACE secrets/$SECRET_NAME --keys=$SECRET_USER_CERT_KEY --to=-)\"; export DST_KEY=\"$(oc extract -n $DST_NAMESPACE secrets/$SECRET_NAME --keys=$SECRET_USER_KEY_KEY --to=-)\"; if [ -n \"$SRC_CERT\" ] && [ -n \"$SRC_KEY\" ] && ([ \"$DST_CERT\" != \"$SRC_CERT\" ] || [ \"$DST_KEY\" != \"$SRC_KEY\" ]); then echo 'Values differ. Syncing...'; oc create secret generic -n $DST_NAMESPACE --dry-run -o yaml $SECRET_NAME --from-literal=\"$SECRET_USER_CERT_KEY=$SRC_CERT\" --from-literal=\"$SECRET_USER_KEY_KEY=$SRC_KEY\" | oc apply -f -; fi;"]
          - name: bob-sync
            image: openshift/origin-cli
            env:
            - name: SRC_NAMESPACE
              value: "strimzi"
            - name: DST_NAMESPACE
              value: "fuse"
            - name: SECRET_NAME
              value: "bob"
            - name: SECRET_KEY
              value: "password"
            command: ["bash",  "-c", "export SRC=\"$(oc extract -n $SRC_NAMESPACE secrets/$SECRET_NAME --keys=$SECRET_KEY --to=-)\"; export DST=\"$(oc extract -n $DST_NAMESPACE secrets/$SECRET_NAME --keys=$SECRET_KEY --to=-)\"; if [ -n \"$SRC\" ] && [ \"$DST\" != \"$SRC\" ]; then echo 'Values differ. Syncing...'; oc create secret generic -n $DST_NAMESPACE --dry-run -o yaml $SECRET_NAME --from-literal=\"$SECRET_KEY=$SRC\" | oc apply -f -; fi;"]
