# Servlet Container & Health Setup
server:
  address: 0.0.0.0
management:
  address: 0.0.0.0
  port: 8081
endpoints:
  enabled: false
  health:
    enabled: true

# Camel Spring Boot
camel:
  springboot:
    name: CamelKafkaAuthz
  component:
    kafka:
      configuration:
        brokers: my-cluster-kafka-bootstrap-strimzi.192.168.99.100.nip.io:443
        sslTruststoreLocation: /Users/jreagan/Development/Projects/Other_Projects/joshdreagan/camel-kafka-authz/truststore.p12
        sslTruststorePassword: Abcd1234
        sslTruststoreType: PKCS12
        sslKeystoreType: PKCS12

# Logging
logging:
  config: classpath:logback.xml
  level:
    #org.apache: DEBUG
    #org.apache.camel: DEBUG
    org.apache.camel.examples: DEBUG